# Generated by Django 2.2.5 on 2019-11-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20191108_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movielist',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
