# Generated by Django 2.2.5 on 2020-07-08 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_latestlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LatestList',
        ),
        migrations.DeleteModel(
            name='PopularList',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='watchlist',
        ),
        migrations.DeleteModel(
            name='Recommend',
        ),
        migrations.DeleteModel(
            name='Watch',
        ),
    ]
