# Generated by Django 2.2.5 on 2020-07-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20200708_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('popularity', models.FloatField()),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
            ],
        ),
    ]
