# Generated by Django 2.2.5 on 2020-07-09 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('popularity', models.FloatField()),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('watched', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.WatchList')),
            ],
        ),
    ]
